@dev = http://localhost:3003
# @prod = 

@baseUrl = {{dev}}

POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0IiwiaWQiOiI2YTg1Nzc2Y2FmNGVmN2VmZDZlZWFiOWYiLCJpYXQiOjE3ODcxMzE4NDZ9.fgZBUTAcGcrSsXMJtoM5VBIiXoLKwCzcksuUrgJPV2U

{
    "url": "yet another url",
    "title": "yet another title",
    "author": "yet another author",
    "likes": 0
}
