@dev = http://localhost:3003
# @prod = 

@baseUrl = {{dev}}

POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "title": "test blog",
    "author": "test author",
    "url": "test url",
    "likes": 0
}
