@dev = http://localhost:3003
# @prod = 

@baseUrl = {{dev}}

POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "second",
    "password": "pswd",
    "name": "second user"
}
