@dev = http://localhost:3003
# @prod = 

@baseUrl = {{dev}}

POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2YTJkMzE2ZjcyZTU3NGIyNzVhYzgxNzIiLCJpYXQiOjE3ODYxMzIyMDd9.0A-ouYamO_47EHGCY8jagMDfLCyszGktTAFOqYmnN5g

{
    "url": "url",
    "title": "with userExtractor",
    "author": "author",
    "likes": 0
}
