@dev = http://localhost:3003
# @prod = 

@baseUrl = {{dev}}

DELETE {{baseUrl}}/api/blogs/6a8578d4af4ef7efd6eeaba4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0IiwiaWQiOiI2YTg1Nzc2Y2FmNGVmN2VmZDZlZWFiOWYiLCJpYXQiOjE3ODcxMzE4NDZ9.fgZBUTAcGcrSsXMJtoM5VBIiXoLKwCzcksuUrgJPV2U