@dev = http://localhost:3001
@prod = https://phonebook-khor.onrender.com

@baseUrl = {{dev}}

POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name": "new contact",
    "number": "1234567"
}
