@dev = http://localhost:3001
@prod = https://phonebook-khor.onrender.com

@baseUrl = {{dev}}

PUT {{baseUrl}}/api/persons/6a1afea62e4fb18b52ed4358
Content-Type: application/json

{
    "name": "Keeks",
    "number": "0000000"
}